import fs from "fs";
import path from "path";
import type { Logger } from "./logger.js";

const CACHE_VERSION = 2;
const DEFAULT_CACHE_FILE = ".notion-content-gen-cache.json";

export type CacheEntry = {
  lastEditedTime: string;
  filePath: string;
};

/**
 * Per-root cache slice. Keyed by Notion node id. Each entry records the
 * page's `last_edited_time` and the resolved output `filePath` so a
 * subsequent run can decide whether the file is still up to date.
 */
export type CacheRoot = {
  entries: Record<string, CacheEntry>;
};

/**
 * On-disk cache shape. Keyed by Notion root id so multi-root setups can
 * share a single sidecar file friendly to CI cache restoration.
 */
export type CacheData = {
  version: number;
  roots: Record<string, CacheRoot>;
};

export function emptyCache(): CacheData {
  return { version: CACHE_VERSION, roots: {} };
}

export function emptyRoot(): CacheRoot {
  return { entries: {} };
}

export function resolveCachePath(
  cache: boolean | string | undefined,
  cwd: string = process.cwd(),
): string | null {
  if (cache === false) return null;
  if (typeof cache === "string") return path.resolve(cwd, cache);
  return path.resolve(cwd, DEFAULT_CACHE_FILE);
}

export function loadCache(cachePath: string | null): CacheData {
  if (!cachePath || !fs.existsSync(cachePath)) return emptyCache();
  try {
    const raw = JSON.parse(fs.readFileSync(cachePath, "utf-8"));
    if (
      raw?.version !== CACHE_VERSION ||
      typeof raw.roots !== "object" ||
      raw.roots === null
    ) {
      return emptyCache();
    }
    return raw as CacheData;
  } catch {
    return emptyCache();
  }
}

export function saveCache(
  cachePath: string | null,
  cache: CacheData,
): void {
  if (!cachePath) return;
  const dir = path.dirname(cachePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(cachePath, JSON.stringify(cache, null, 2));
}

export type StaleCleanupOptions = {
  /** Resolved root of generated content; cleanup never escapes this dir. */
  contentDir: string;
  /** When true, log what would be removed without touching disk. */
  dryRun?: boolean;
  logger?: Logger;
};

export type StaleCleanupResult = {
  removed: string[];
  skipped: string[];
};

/**
 * Removes files that the previous cache claimed ownership of but the new
 * cache no longer does — pages deleted, renamed, or moved in Notion since
 * the last run. After removing files, prunes any directories that became
 * empty (walking from deepest to shallowest), but never removes `contentDir`
 * itself.
 *
 * Operates on per-root cache slices so multi-root setups can scope cleanup
 * to each root's `contentDir` independently — deleting a page in root A
 * cannot touch root B's files.
 *
 * Safety: only paths recorded in `oldRoot` are eligible for removal. Files
 * that exist in `contentDir` but were not generated by this tool are never
 * touched. Paths that escape `contentDir` are skipped defensively.
 */
export function cleanupStaleFiles(
  oldRoot: CacheRoot,
  newRoot: CacheRoot,
  options: StaleCleanupOptions,
): StaleCleanupResult {
  const { contentDir, dryRun = false, logger } = options;
  const resolvedRoot = path.resolve(contentDir);
  const newPaths = new Set(
    Object.values(newRoot.entries).map((entry) => path.resolve(entry.filePath)),
  );

  const removed: string[] = [];
  const skipped: string[] = [];
  const dirsToCheck = new Set<string>();

  for (const oldEntry of Object.values(oldRoot.entries)) {
    const abs = path.resolve(oldEntry.filePath);
    // Skip paths that are still owned (page kept the same filePath, or another
    // page now writes to this path) — only orphaned paths should be removed.
    if (newPaths.has(abs)) continue;
    if (!isWithin(abs, resolvedRoot)) {
      skipped.push(abs);
      continue;
    }
    if (!fs.existsSync(abs)) continue;

    if (dryRun) {
      logger?.info(`[dry-run] would remove stale: ${abs}`);
    } else {
      try {
        fs.rmSync(abs, { force: true });
        logger?.debug(`removed stale: ${abs}`);
      } catch (err) {
        logger?.warn(`Failed to remove stale file ${abs}: ${(err as Error).message}`);
        continue;
      }
    }
    removed.push(abs);
    dirsToCheck.add(path.dirname(abs));
  }

  if (!dryRun) pruneEmptyDirs(dirsToCheck, resolvedRoot, logger);
  return { removed, skipped };
}

function isWithin(child: string, parent: string): boolean {
  const rel = path.relative(parent, child);
  return rel !== "" && !rel.startsWith("..") && !path.isAbsolute(rel);
}

/**
 * Removes any directory in `dirs` that has become empty, walking upward toward
 * `root` so a chain of newly-emptied ancestors collapses too. Never removes
 * `root` itself. Exported so plugins that write (and clean up) their own
 * sidecar files can reuse the same pruning logic core uses for page files.
 */
export function pruneEmptyDirs(
  dirs: Set<string>,
  root: string,
  logger: Logger | undefined,
): void {
  // Sort deepest-first so we collapse children before their parents.
  const ordered = [...dirs].sort((a, b) => b.length - a.length);
  for (const dir of ordered) {
    let current = dir;
    while (isWithin(current, root) && current !== root) {
      if (!fs.existsSync(current)) {
        current = path.dirname(current);
        continue;
      }
      let entries: string[];
      try {
        entries = fs.readdirSync(current);
      } catch {
        break;
      }
      if (entries.length > 0) break;
      try {
        fs.rmdirSync(current);
        logger?.debug(`removed empty dir: ${current}`);
      } catch {
        break;
      }
      current = path.dirname(current);
    }
  }
}
