import fs from "fs";
import path from "path";
import type { Logger } from "./logger.js";

const CACHE_VERSION = 1;
const DEFAULT_CACHE_FILE = ".notion-content-gen-cache.json";

export type CacheEntry = {
  lastEditedTime: string;
  filePath: string;
};

export type CacheData = {
  version: number;
  pages: Record<string, CacheEntry>;
};

export function emptyCache(): CacheData {
  return { version: CACHE_VERSION, pages: {} };
}

export function resolveCachePath(
  cache: boolean | string | undefined,
  cwd: string = process.cwd(),
): string | null {
  if (cache === false) return null;
  if (typeof cache === "string") return path.resolve(cwd, cache);
  return path.resolve(cwd, DEFAULT_CACHE_FILE);
}

export function loadCache(cachePath: string | null): CacheData {
  if (!cachePath || !fs.existsSync(cachePath)) return emptyCache();
  try {
    const raw = JSON.parse(fs.readFileSync(cachePath, "utf-8"));
    if (raw?.version !== CACHE_VERSION || typeof raw.pages !== "object") {
      return emptyCache();
    }
    return raw as CacheData;
  } catch {
    return emptyCache();
  }
}

export function saveCache(
  cachePath: string | null,
  cache: CacheData,
): void {
  if (!cachePath) return;
  const dir = path.dirname(cachePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(cachePath, JSON.stringify(cache, null, 2));
}

export type StaleCleanupOptions = {
  /** Resolved root of generated content; cleanup never escapes this dir. */
  contentDir: string;
  /** When true, log what would be removed without touching disk. */
  dryRun?: boolean;
  logger?: Logger;
};

export type StaleCleanupResult = {
  removed: string[];
  skipped: string[];
};

/**
 * Removes files that the previous cache claimed ownership of but the new
 * cache no longer does — pages deleted, renamed, or moved in Notion since
 * the last run. After removing files, prunes any directories that became
 * empty (walking from deepest to shallowest), but never removes `contentDir`
 * itself.
 *
 * Safety: only paths recorded in `oldCache` are eligible for removal. Files
 * that exist in `contentDir` but were not generated by this tool are never
 * touched. Paths that escape `contentDir` are skipped defensively.
 */
export function cleanupStaleFiles(
  oldCache: CacheData,
  newCache: CacheData,
  options: StaleCleanupOptions,
): StaleCleanupResult {
  const { contentDir, dryRun = false, logger } = options;
  const resolvedRoot = path.resolve(contentDir);
  const newPaths = new Set(
    Object.values(newCache.pages).map((entry) => path.resolve(entry.filePath)),
  );

  const removed: string[] = [];
  const skipped: string[] = [];
  const dirsToCheck = new Set<string>();

  for (const oldEntry of Object.values(oldCache.pages)) {
    const abs = path.resolve(oldEntry.filePath);
    // Skip paths that are still owned (page kept the same filePath, or another
    // page now writes to this path) — only orphaned paths should be removed.
    if (newPaths.has(abs)) continue;
    if (!isWithin(abs, resolvedRoot)) {
      skipped.push(abs);
      continue;
    }
    if (!fs.existsSync(abs)) continue;

    if (dryRun) {
      logger?.info(`[dry-run] would remove stale: ${abs}`);
    } else {
      try {
        fs.rmSync(abs, { force: true });
        logger?.debug(`removed stale: ${abs}`);
      } catch (err) {
        logger?.warn(`Failed to remove stale file ${abs}: ${(err as Error).message}`);
        continue;
      }
    }
    removed.push(abs);
    dirsToCheck.add(path.dirname(abs));
  }

  if (!dryRun) pruneEmptyDirs(dirsToCheck, resolvedRoot, logger);
  return { removed, skipped };
}

function isWithin(child: string, parent: string): boolean {
  const rel = path.relative(parent, child);
  return rel !== "" && !rel.startsWith("..") && !path.isAbsolute(rel);
}

function pruneEmptyDirs(
  dirs: Set<string>,
  root: string,
  logger: Logger | undefined,
): void {
  // Sort deepest-first so we collapse children before their parents.
  const ordered = [...dirs].sort((a, b) => b.length - a.length);
  for (const dir of ordered) {
    let current = dir;
    while (isWithin(current, root) && current !== root) {
      if (!fs.existsSync(current)) {
        current = path.dirname(current);
        continue;
      }
      let entries: string[];
      try {
        entries = fs.readdirSync(current);
      } catch {
        break;
      }
      if (entries.length > 0) break;
      try {
        fs.rmdirSync(current);
        logger?.debug(`removed empty dir: ${current}`);
      } catch {
        break;
      }
      current = path.dirname(current);
    }
  }
}
